### PR TITLE
update weather db url to https

### LINKED ISSUE #461: link weather db to cassavabase

### PR DESCRIPTION
**Pull request by bellerbrock**
Description 
-----------------------------------------------------
Fixes trial detail page weather links by updating the weather db url now that rtbbase is on https 

closes #461

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by lukasmueller** [comment]
Does this change acutally pull in the  weather data?

**Review by afpowell — APPROVED** [review]
👍

**Comment by bellerbrock** [comment]
@lukasmueller it fixes the existing functionality, which is to check the trial location against the list of locations with weather in the weather db, and create a link to view that data if it exists.

@afpowell Good catch, the created links were still working with just http, but safer to update them too!

**Review by lukasmueller — APPROVED** [review]
:-)

**Pull request merged**
