### PR TITLE
Checkbox to use tissue numbers 

### PR DESCRIPTION
**Pull request by Sri-2023**
Description 
-----------------------------------------------------

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by bellerbrock** [comment]
@Sri-2023 looks like the AddPlantsandTissueSamplesToTrial.t test is failing and needs to be updated, which makes sense since this PR modifies the `create_tissue_samples` subroutine. [Here's one place](https://github.com/solgenomics/sgn/blob/5548d23d7d40bc1b55d006debd2a1663b9c7fc15/t/unit_fixture/CXGN/Trial/AddPlantsandTissueSamplesToTrial.t#L1456) at least where the subroutine is used within the test and will need an extra value passed to it to represent the 'use_tissue_numbers' argument.

**Review by darekbienkowski — CHANGES_REQUESTED** [review]
We need to describe functionality better.
At the moment, numbering works based on the number of tissues - as before - but now we also have tissues without numbers where they are still counted. That means if we add third tissue to a trial where the first two were without a number is still counted as third - like in a test that I updated. 
I don't know if it is correct behavior. 

```
  'test_trial25_plant_2_leaf',    # sample without tissue number
  'test_trial25_plant_2_root2',   # sample with tissue number
  'test_trial25_plant_2_fruit3'   # sample with tissue number

```

**Review by bellerbrock — COMMENTED** [review]
The test fix looks good.

In terms of documenting or modifying the tissue numbering behavior - should it be specific to the tissue type/prefix? That would make the most sense to me. For example: 

  'test_trial25_plant_2_leaf',    # sample without tissue number
  'test_trial25_plant_2_root1',   # sample with tissue number
  'test_trial25_plant_2_fruit1'   # sample with tissue number
  'test_trial25_plant_2_fruit2'   # sample with tissue number

**Comment by darekbienkowski** [comment]
Ok. Then I will later change the functionality not to count unnumbered tissues to a global tissues index.

**Comment by darekbienkowski** [comment]
@Sri-2023 @bellerbrock I changed the test and Perl code for probably correct treating tissue without numbers, but can you check in UI if it works? I don't have a clue where that functionality is...

**Review by bellerbrock — APPROVED** [review]
The current version works fine for me. The checkbox makes it easy to turn off numbering, which is what Prasad and others were asking for.

And Darius's changes to improve the numbering when it is used looks good. Could enhance it even more to be prefix specific, but doubt that's worth the effort unless it's specifically requested.   

@darekbienkowski the code being changed can be tested in the web interface by going to Manage -> Tissue Samples -> then clicking on 'Create Tissue Samples for Field Trial'

**Review by darekbienkowski — APPROVED** [review]
;-)

**Pull request merged**
