### PR TITLE
Topic/cache file system for genotype search

### LINKED ISSUE #2731: genotype search is slow
Expected Behavior 
--------------------------------------------------------------------------
We can cache search queries and results in files for speed.
This is safe because genotypes do not change frequently (or at all) once a protocol is loaded

For Bugs:
---------

### PR DESCRIPTION
**Pull request by nickmorales**
Description 
-----------------------------------------------------
wizard genotype download (DosageMatrix and VCF) and GRM download uses cached queries for speed

closes #2731 

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by lukasmueller** [comment]
Does this use the iterator code? I think that would be important for limiting the memory usage.

**Comment by nickmorales** [comment]
This doesnt use the iterator but in a future version it could to write the cached file in cxgn::dataset::cache

**Comment by lukasmueller** [comment]
Adrian, will you convert this to use the iterator?

cheers
Lukas

**Comment by afpowell** [comment]
Yes, but I am doing this on topic/wizard_genotype_download_large_files

**Pull request merged**
