### PR TITLE
remove stock owner from search for speeding up search

### PR DESCRIPTION
**Pull request by nmenda**
Description 
-----------------------------------------------------

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by lukasmueller** [comment]
it's a bit faster I think.
But when I added another property ("organization") to the search and the search never returned
I think the default should be "starts with..." or "exactly", not contains, as that is a slower search

**Comment by titima15** [comment]
Screenshot 2023-06-23 at 2 14 00 PM

**Comment by titima15** [comment]
@nmenda I kept getting this error whenever I added additional property.

**Comment by darekbienkowski** [comment]
@titima15 Please check now search result table with fixed header

image

**Review by darekbienkowski — APPROVED** [review]
;-)

**Comment by titima15** [comment]
@darekbienkowski I informed Naama last Friday about the datatable warning. She might look into it already.  It would be redundant with her fix (even though it's an easy fix). Did you check with her first before pushing the commit?

**Review by titima15 — APPROVED** [review]

**Pull request merged**
