### PR TITLE
Geo fieldmap with brapiv2

### PR DESCRIPTION
**Pull request by MFlores2021**
Description 
-----------------------------------------------------

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Review by lukasmueller — APPROVED** [review]
:-) This is so amazing!!!

**Comment by nickmorales** [comment]
This is very cool!
However, when I try to save the coords I get a "401 (unauthorized)" for the /brapi/v2/observationunits/stock_id PUT call. Maybe I am missing something?

**Comment by lukasmueller** [comment]
Are you logged in?

cheers
Lukas
________________________________

**Comment by nickmorales** [comment]
Yes I am logged in as a curator. I tested it on a HTTPS connection to double check, but same problem as before.

**Pull request merged**
