### PR TITLE
remove d3v4 lfrom fieldmap.mas

### PR DESCRIPTION
**Pull request by isaak**
Description 
-----------------------------------------------------
-- remove duplicate d3 loading from fieldmap mason template and fix conflict with a d3 version loaded in fieldmap.js

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Review by lukasmueller — APPROVED** [review]
:-)

**Review by nmenda — APPROVED** [review]

**Review by lukasmueller — APPROVED** [review]
:-)

**Comment by dwaring87** [comment]
It looks like this is required for the geo field map to work (the "Edit Geo Field Layout" button).  The map shows up when d3v4 is loaded but does not when it's removed.

**Comment by lukasmueller** [comment]
Let's fix the geo field layout next.

**Pull request merged**
