### PR TITLE
lists and datasets loading speed improvement

### PR DESCRIPTION
**Pull request by isaak**
Description 
-----------------------------------------------------

-- Improves significantly lists and datasets loading speed in solGS analysis tools
-- adds 'search in progress' feedback

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by afpowell** [comment]
Hi Isaak - the clustering page doesn't seem to be loading correctly for me on this branch. It works on master though, as well as on this branch for the other tools. I haven't been able to find the reason for it in the code yet... it is basically just showing the headers of the table and nothing else.

**Review by nmenda — APPROVED** [review]

**Comment by isaak** [comment]
> Hi Isaak - the clustering page doesn't seem to be loading correctly for me on this branch. It works on master though, as well as on this branch for the other tools. I haven't been able to find the reason for it in the code yet... it is basically just showing the headers of the table and nothing else.

I wonder if  hard refreshing the page would help... it might be old cached js code on the browser???
Could you check here: https://cassava-test.sgn.cornell.edu/cluster/analysis/

**Comment by afpowell** [comment]
Yep, good call - clearing the cache did the trick

**Review by afpowell — APPROVED** [review]
:+1:

**Pull request merged**
