### PR TITLE
Download archived VCF files

### PR DESCRIPTION
**Pull request by dwaring87**
Description 
-----------------------------------------------------

We've had some users want to download entire genotyping projects from the database.  This can be very slow for larger projects since the VCF file has to be recreated from the data queried from the database.

This adds the ability to download the original archived VCF files uploaded for genotyping projects stored in the database (similar to the way you can download uploaded files for phenotyping trials).  This is much faster than regenerating the file from the database. There are two ways to download the archived vcf files:

1) From the genotyping project detail page (under a new Archived Files section)
image

2) From the Search Wizard by selecting either one or more genotyping protocols or genotyping projects.  The new Archived Genotype Data section will include links to download the VCF files for any matching projects in the database.
image

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by titima15** [comment]
@dwaring87 for the vcf archived file shown in the first snap shot, did you upload using script or user interface? Looks like vcf files uploaded via user interface were not stored in vcf format

**Comment by titima15** [comment]
@dwaring87 thanks for the change. Now the file has vcf format. One small issue though. The file names in the archived table  (on my machine) don't have .vcf (that's why I asked in the lab meeting). When I tested downloading the file, the file content has vcf format, but the file name still didn't have .vcf. This might be an issue for users.

**Comment by dwaring87** [comment]
@titima15 Thanks for checking again.  I'm not sure why the archived files could be missing the extension, but I could try to add the .vcf extension to the downloaded file if its missing from the archived file.

**Comment by titima15** [comment]
@dwaring87 perfect, thanks

**Review by titima15 — APPROVED** [review]

**Review by Sri-2023 — COMMENTED** [review]
:)

**Review by Sri-2023 — APPROVED** [review]
:)

**Pull request merged**
