### PR TITLE
update solGS dataset and list pops selection interface

### PR DESCRIPTION
**Pull request by isaak**
Description 
-----------------------------------------------------

-- update dataset/list selection interface for solGS

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Review by lukasmueller — CHANGES_REQUESTED** [review]
When I click on "Create training Population" a prompt is displayed if you would like to run it in the background, with the option "Yes" and "Cancel". Shouldn't there be an option "No" ?

**Review by lukasmueller — COMMENTED** [review]
Maybe the Dataset set option should be the first one and the trials and "search a trait" interface should be below it?

**Review by afpowell — APPROVED** [review]
:+1:

**Review by lukasmueller — APPROVED** [review]
:-)

**Pull request merged**
