### PR TITLE
add script to load user accounts

### PR DESCRIPTION
**Pull request by lukasmueller**
Description 
-----------------------------------------------------
Script loads user data from an xlsx file

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by dwaring87** [comment]
@lukasmueller I tried running the load script on my local instance and get this error:

```
DATA: $VAR1 = {                                                                                                                                                                                
'last_name' => 'Testing123',                                                                                                                                                         
'email' => 'dwaring87+testing1@gmail.com',                                                                                                                                           
'first_name' => 'Test',                                                                                                                                                              
'username' => 'testing1',                                                                                                                                                            
'organization' => 'Cornell University' 
}; 
Test    Testing123      testing1        dwaring87+testing1@gmail.com    atigyeel                                                                                                     

you forgot the table name argument to last_insert_id                                                                                                                                 

An error occured! Rolling back!{UNKNOWN}: Died at /home/production/cxgn/cxgn-corelibs/lib/CXGN/DB/Connection.pm line 743. at ./load_people.pl line 225                                                         
```

Are there any steps I'd have to do first to get this to work?

**Comment by lukasmueller** [comment]
@dwaring87 you need a change in the cxgn-corelibs as well. I will commit it asap.

**Comment by dwaring87** [comment]
@lukasmueller The update to cxgn-corelibs fixes the error.  Not sure why the tests aren't passing, they passed on your previous commit...

**Review by dwaring87 — APPROVED** [review]

**Comment by darekbienkowski** [comment]
I will check tests.

**Review by afpowell — APPROVED** [review]
:^)

**Pull request merged**
