### PR TITLE
Topic/identifier generation

### LINKED ISSUE #2112: agronomy project label generation assistance
Expected Behavior 
--------------------------------------------------------------------------

Label generation for ACAI and the Banana Agronomy Project is a centrally managed process:
From the office they will just print a pile of barcodes for their entities (fields, trials, plots, etc) and then distribute the labels to locations. the trial is then "assembled" on-the-fly using ODK by first tagging a field to a gps location, then tagging a trial to a field, then tagging plots to a trial, then tagging plants to plots, etc

Barcodes have an ID and a barcode on them in the format:
ACTLNG000001
First 2 letters are project (AC or BN for ACAI and Banana Agronomy)
Second 2 letters are Entity (TL: Trial, FD: Field, FB: Fieldbook, PA: Plant, PS: Plantsample, PO: Plot, SE: Section, SS: Soilsample)
Third 2 letters are Country
Last 6 digits are just incremented as they go

What we need is a page to assist in managing the printing of these barcodes by remembering what the last entity number is, so that they can say "give me the next 5 trial barcodes and next 500 plot barcodes".

For Bugs:
---------

### PR DESCRIPTION
**Pull request by nickmorales**
Description 
-----------------------------------------------------
Implements a page for managing identifier generation. Identifier generation is important for ACAI and Banana Agronomy Project where barcode identifiers are pre-printed and then assigned in the field. Identifier generation can also be important for pre-printing identifiers that are later assigned to samples in the lab.

closes #2112 

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [x] New feature
  - [x] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.

### CODE REVIEW

**Comment by aco46** [comment]
@nickmorales I tried it on my local machine as well as yambase-test, it gives same error. See error below;

Caught exception in SGN::Controller::AJAX::IdentifierGeneration->identifier_generation_list "malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /home/vagrant/cxgn/sgn/bin/../lib/SGN/Controller/AJAX/IdentifierGeneration.pm line 100."

**Comment by nickmorales** [comment]
@aco46 thanks for testing this.. i will debug it on yambase-test because it works for me on my machine...

**Comment by aco46** [comment]
You may have to move it back to your topic branch to be able to debug it. I checked it back to the last tag.

**Comment by nickmorales** [comment]
@aco46 it should be fixed now thanks. you can test it out here or on your machine https://yambase-test.sgn.cornell.edu/breeders/identifier_generation

**Pull request merged**
