### PR TITLE
add a bulk accession rename feature

### PR DESCRIPTION
**Pull request by lukasmueller**
Description 
-----------------------------------------------------

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [x] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [x] User-Facing Change
    - [x] The user manual in `/docs` has been updated.
  - [x] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by titima15** [comment]
Screen Shot 2022-12-12 at 9 52 02 AM

**Comment by titima15** [comment]
Need to fix typo and line format

**Comment by afpowell** [comment]
r.e. lines ~40-47 in upload_accession_rename_dialog.mas:
The confirmation of the successful renames is a 'textarea' element, which lets the user delete/type things in the dialog box. It should be a different type of element maybe? It might seem a bit confusing to users as is.
Also, the "Already in the system" box seems to be unnecessary here (the jquery related to it looks like it is commented out, but the element in the mason file is not).

**Review by titima15 — APPROVED** [review]
👍

**Review by afpowell — APPROVED** [review]

**Pull request merged**
