### PR TITLE
Topic/audit tables patch

### LINKED ISSUE #4237: Create auditing system
Expected Behavior 
--------------------------------------------------------------------------
Implement backend that can track changes to the database

For Bugs:
---------

### PR DESCRIPTION
**Pull request by afpowell**
Description 
-----------------------------------------------------

Closes #4237

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [X] New feature
  - [X] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by afpowell** [comment]
From my testing, these seem to be the unaltered audit tables:

cvterm_dbxref_audit
cvtermprop_audit 
cvtermsynonym_audit 
dbxrefprop_audit 
nd_experiment_contact_audit                       
nd_experiment_dbxref_audit 
nd_experiment_pub_audit  
nd_experiment_stock_dbxref_audit                  
nd_experiment_stockprop_audit    
nd_protocol_reagent_audit                         
nd_reagent_audit                                  
nd_reagentprop_audit                              
nd_reagent_relationship_audit
organism_dbxref_audit                             
organismpath_audit                                
organismprop_audit                                
organism_relationship_audit 
phenotype_cvterm_audit   
phenotypeprop_audit
project_contact_audit                             
project_pub_audit
pubabstract_audit                                 
pub_audit                                         
pubauthor_audit                                   
pub_dbxref_audit                                  
pubprop_audit                                     
pub_relationship_audit 
sp_organization_audit
stockcollection_audit                             
stockcollectionprop_audit                         
stockcollection_stock_audit 
stock_cvterm_audit                                
stock_cvtermprop_audit                            
stock_dbxref_audit                                
stock_dbxrefprop_audit                            
stock_genotype_audit  
stockprop_pub_audit                               
stock_pub_audit

**Review by darekbienkowski — APPROVED** [review]

**Review by chris263 — APPROVED** [review]
+1:

**Comment by lukasmueller** [comment]
Note from the labmeeting today: phenotype upload showed spinning wheel on this branch with a error containing phenotype file (did not show an error message). This may not be specific to this branch though... will test more.

**Comment by lukasmueller** [comment]
Could be a docker config issue on cassava-devel

**Review by alockrow — APPROVED** [review]

**Pull request merged**
