### PR TITLE
add more types of searches to quicksearch

### PR DESCRIPTION
**Pull request by lukasmueller**
Description 
-----------------------------------------------------
Quick fix to add more search types. 
Quick search test was moved from the legacy directory to the t/unit_mech/Controller directory, and updated with new test.

Still, needs extensive refactoring, should be converted to AJAX.

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [x] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by dwaring87** [comment]
[Fix Quick Search](https://trello.com/c/xOvzCncf/21-fix-quick-search)

**Comment by lukasmueller** [comment]
Hi David, I can't see the trello board in the link above... it's set to private.

**Comment by dwaring87** [comment]
Oops, I guess Trello automatically added that.  We had removed the Quick Search from our instances since we noticed it wasn't working with some data types and this was a back-burnered trello task to look into at some point.  But you've fixed it!  So I linked the PR to remind us to look into it again.

**Review by titima15 — APPROVED** [review]
👍

**Pull request merged**
