### PR TITLE
switch to correct projectprop for planting date and harvest date

### PR DESCRIPTION
**Pull request by nmenda**

### CODE REVIEW

**Comment by nickmorales** [comment]
When adding a planting or harvest date from the trial detail page or from the calendar, it uses 'harvest_date' and 'planting_date'

**Comment by nmenda** [comment]
we need to change one of those and decide on one projectprop

**Comment by nmenda** [comment]
the cvterm we have in the database and the fixture is 'project planting date'

**Comment by lukasmueller** [comment]
change everything to trial_planting_date and trial_harvest_date from project_*_data and *_date

**Comment by nmenda** [comment]
cassavabase has many projectprops linked to both terms - 'planting_date' and 'project planting date'

need to merge these into one cvterm

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/pull/1158

**Comment by nickmorales** [comment]
Was this solved by the other pull request? @nmenda

**Comment by nmenda** [comment]
@nickmorales which pull request? is there a duplicated one ?

**Comment by nickmorales** [comment]
@naama #1158 was similar i thought

**Comment by nmenda** [comment]
@nickmorales you're right , the other pull requests resolves this. I'm deleting this branch

**Pull request closed without merging**
