### PR TITLE
List Editor: add link to item detail page

### LINKED ISSUE #5097: Add link to individual accession page from list contents window
Expected Behavior 
--------------------------------------------------------------------------

For Bugs:
---------

#### Steps to Reproduce

Screenshot 2024-09-09 at 10 55 14 AM

### PR DESCRIPTION
**Pull request by dwaring87**
Description 
-----------------------------------------------------

This adds a link next to each list item in the list editor to that item's detail page:

image

Fixes #5097 

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by alockrow** [comment]
I'm not seeing the change in my local fixture when I check out the branch. 

image

**Review by lukasmueller — APPROVED** [review]
:-)

**Comment by lukasmueller** [comment]
@alockrow did you reload the page? It appears after that

**Review by alockrow — APPROVED** [review]
Seems to be working now. Not sure why it didn't before.

**Pull request merged**
