### PR TITLE
Enable select all seedlots in available seedlots dialog

### PR DESCRIPTION
**Pull request by ryan-preble**
…toggled, all checkboxes in the open available seedlots modal are selected/deselected. List creation works. Disabled checkboxes are ignored.

Description 
-----------------------------------------------------
Added a javascript function to enable users to select/deselect all available seedlots in the available seedlots modal. Disabled seedlots are ignored. Works with list creation. 

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by afpowell** [comment]
Hi Ryan, this looks really nice - I only had one minor comment: in the case where someone selects a list made up entirely of accessions that don't have any available seedlots, the Select All box is still enabled and clickable, which could be misleading. In that scenario, it might be good to have it disabled in the same way that the check boxes are for the individual accessions in the list.

**Comment by ryan-preble** [comment]
> Hi Ryan, this looks really nice - I only had one minor comment: in the case where someone selects a list made up entirely of accessions that don't have any available seedlots, the Select All box is still enabled and clickable, which could be misleading. In that scenario, it might be good to have it disabled in the same way that the check boxes are for the individual accessions in the list.

Ok, I will change it to hide the select all button if the seedlots list is empty

**Review by afpowell — APPROVED** [review]
:+1:

**Review by Sri-2023 — APPROVED** [review]
👍

**Pull request merged**
