### PR TITLE
display genotype data missing warning

### PR DESCRIPTION
**Pull request by isaak**
Description 
-----------------------------------------------------
-- rename html elements attribute names for ease or understanding and maintainance
-- Show a message to a user to select a genotyping protocol  or upload genotype data before trying to use solGS tools that need genotype data,  in websites with no default genotyping protocol settings or no genotype data.
image

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Review by afpowell — APPROVED** [review]
:+1:
I would just recommend that, in the warning/error message text, you remove the "a" from the line "use the tool on a genotype data"

**Review by lukasmueller — COMMENTED** [review]
On the fixture, there is some genotyping data and there is also a protocol. When I select the protocol, the message still appears. Shouldn't it disappear at this point?

**Comment by isaak** [comment]
> On the fixture, there is some genotyping data and there is also a protocol. When I select the protocol, the message still appears. Shouldn't it disappear at this point?

Good catch. Fixed 481fd71. Many thanks.

**Review by lukasmueller — APPROVED** [review]
:-)

**Pull request merged**
