### PR TITLE
fixed pedigree viewer when panel if collapsed

### PR DESCRIPTION
**Pull request by darekbienkowski**
Description 
-----------------------------------------------------

{breedbase_address}/stock/XXXX/view

Changes in event trigger based on xpath. If something is wrong with the UI - it should trigger the pedigree viewer as before - without checking if the panel is open or not. 

image17

Screenshot from 2024-01-29 09-56-54

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [x] Bug fix
  - [x] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Comment by darekbienkowski** [comment]
https://github.com/solgenomics/sgn/issues/4771

**Review by MFlores2021 — APPROVED** [review]

**Review by nmenda — APPROVED** [review]

**Comment by dwaring87** [comment]
@darekbienkowski I'm not sure if I'm having a problem with cached files or if there's something else going on, but I'm still having issues with the pedigree viewer.

This is the view when the panel is collapsed by default and then expanded:
image

This is the view when the panel is expanded by default:
image

Any thoughts on what to look into?

**Comment by dwaring87** [comment]
I see a difference now:  I was collapsing the outer "Pedigree" section by default.  Collapsing the inner "Pedigree and Descendants" section by default works (when keeping the outer section expanded).

**Comment by lukasmueller** [comment]
I think the inner section does not need a collapse capability

**Comment by darekbienkowski** [comment]
> I see a difference now: I was collapsing the outer "Pedigree" section by default. Collapsing the inner "Pedigree and Descendants" section by default works (when keeping the outer section expanded).

Ok. I will check the behavior for the outer section.

**Comment by dwaring87** [comment]
@darekbienkowski I just added a commit to this branch that moves the render trigger to the outer section instead of the inner section.  Can you take a look?

**Pull request merged**
