### PR TITLE
Add dedicated testing configuration

### PR DESCRIPTION
**Pull request by ctucker3**
Description 
-----------------------------------------------------

Addresses issue: https://github.com/solgenomics/sgn/issues/3519

Changes:
- Added documentation on how to run tests.
- Added a `sgn_test.conf` file that is meant to be untouched so that their is a consistent testing environment
- Added a configuration to the `test_fixture.pl` script so that you can specify the server logs output file. 

I used a file that @MFlores2021 sent me that she said she used for tests. I only use a small subset of the features in BreedBase, so the `sgn_test.conf` file should be looked over to see if it contains all necessary configs. 

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Review by MFlores2021 — COMMENTED** [review]
is is PR included in PR #3533?

**Comment by ctucker3** [comment]
> is is PR included in PR #3533?

Yeah #3353 is based off this branch. I needed to fix the tests in that PR so I needed these code changes to do that. My plan was to get this one merged in first, then merge that one. If there are issues with this PR that significantly delay it, or you don't want this work merged in, I can modify the #3353 branch to remove these changes.

**Comment by MFlores2021** [comment]
@ctucker3 if you remove the test from #3533. It's ready to merge.
I've been trying the test fixture and mech ... but need to be further checked

**Comment by ctucker3** [comment]
> @ctucker3 if you remove the test from #3533. It's ready to merge.
> I've been trying the test fixture and mech ... but need to be further checked

Alrighty, I'll try and remove those commits tomorrow. Thanks for checking over everything!

**Review by lukasmueller — APPROVED** [review]
:-)

**Pull request merged**
