### PR TITLE
Topic/solgs/dataset selection analysis ii

### PR DESCRIPTION
**Pull request by isaak**
Description 
-----------------------------------------------------

display datasets and lists in datatable for correlation and kinship analysis

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

### CODE REVIEW

**Review by chris263 — APPROVED** [review]
:-)

**Comment by afpowell** [comment]
The data table view looks great in both cases, but I noticed that on my system when I click on the "Run Correlation" and "Run Kinship" buttons, they disappear (this doesn't happen for the PCA and Clustering tools).

**Comment by isaak** [comment]
> The data table view looks great in both cases, but I noticed that on my system when I click on the "Run Correlation" and "Run Kinship" buttons, they disappear (this doesn't happen for the PCA and Clustering tools).

fixed https://github.com/solgenomics/sgn/pull/4972/commits/97ea1a67e6b04ef829f4924fdd119d893847baa3

**Review by afpowell — APPROVED** [review]
:+1:

**Pull request merged**
