### PR TITLE
Initial Merge of New Pedigree Tree Viewer.

### PR DESCRIPTION
**Pull request by dauglyon**
Description 
-----------------------------------------------------

This is the initial merge of the new pedigree tree viewer but does not contain functionality for trait highlighting/overlay. See gif:

moves towards closing #1274

Checklist 
---------------------------------------------------------------------------------------
- [ ] Documentation only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [x] New feature
  - [ ] Relevant tests have been created and run.
  - [x] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [x] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.

### CODE REVIEW

**Comment by nickmorales** [comment]
very cool! i ran into a "uri request too large" error when clicking IITA-TMS-IBA30572. it has over 1000 progeny 
pic

**Comment by lukasmueller** [comment]
Need to POST?

**Comment by dauglyon** [comment]
Yep! Need to POST, this is a traditional David mistake. But easy to fix.


On November 30, 2017 at 11:32:46 AM, Lukas Mueller (notifications@github.com)
wrote:

Need to POST?

> On Nov 30, 2017, at 10:26 AM, Nick Morales <notifications@github.com>
wrote:
>
> very cool! i ran into a "uri request too large" error when clicking
IITA-TMS-IBA30572. it has over 1000 progeny
>
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/solgenomics/sgn/pull/1486#issuecomment-348243458>, or mute
the thread

**Comment by dauglyon** [comment]
@nickmorales it should work now with the new commits

**Pull request merged**
